# Pipelines subpackage

The `opr.pipelines` subpackage contains ready-to-use pipelines for model inference.

## Imports & functions

In [1]:
from hydra.utils import instantiate
import numpy as np
from omegaconf import OmegaConf
from scipy.spatial.transform import Rotation

try:
    from geotransformer.utils.registration import compute_registration_error
except ImportError:
    print("WARNIGN: geotransformer not installed, registration error will not be computed")

from opr.datasets.itlp import ITLPCampus
from opr.pipelines.place_recognition import PlaceRecognitionPipeline
from opr.pipelines.registration import PointcloudRegistrationPipeline


def pose_to_matrix(pose):
    """From the 6D poses in the [tx ty tz qx qy qz qw] format to 4x4 pose matrices."""
    position = pose[:3]
    orientation_quat = pose[3:]
    rotation = Rotation.from_quat(orientation_quat)
    pose_matrix = np.eye(4)
    pose_matrix[:3,:3] = rotation.as_matrix()
    pose_matrix[:3,3] = position
    return pose_matrix


def compute_error(estimated_pose, gt_pose):
    """For the 6D poses in the [tx ty tz qx qy qz qw] format."""
    estimated_pose = pose_to_matrix(estimated_pose)
    gt_pose = pose_to_matrix(gt_pose)
    error_pose = np.linalg.inv(estimated_pose) @ gt_pose
    dist_error = np.sum(error_pose[:3, 3]**2) ** 0.5
    r = Rotation.from_matrix(error_pose[:3, :3])
    rotvec = r.as_rotvec()
    angle_error = (np.sum(rotvec**2)**0.5) * 180 / np.pi
    angle_error = abs(90 - abs(angle_error-90))
    return dist_error, angle_error

def compute_translation_error(gt_pose, pred_pose):
    """For the 4x4 pose matrices."""
    gt_trans = gt_pose[:3, 3]
    pred_trans = pred_pose[:3, 3]
    error = np.linalg.norm(gt_trans - pred_trans)
    return error

def compute_rotation_error(gt_pose, pred_pose):
    """For the 4x4 pose matrices."""
    gt_rot = Rotation.from_matrix(gt_pose[:3, :3])
    pred_rot = Rotation.from_matrix(pred_pose[:3, :3])
    error = Rotation.inv(gt_rot) * pred_rot
    error = error.as_euler('xyz', degrees=True)
    error = np.linalg.norm(error)
    return error

def compute_absolute_pose_error(gt_pose, pred_pose):
    """For the 4x4 pose matrices."""
    rotation_error = compute_rotation_error(gt_pose, pred_pose)
    translation_error = compute_translation_error(gt_pose, pred_pose)
    return rotation_error, translation_error


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


## Usage example - Place Recognition Pipeline

### Config

In [2]:
DATABASE_TRACK_DIR = "/home/docker_opr/Datasets/ITLP-Campus-data/subsampled_data/outdoor/old/00_2023-02-10"
QUERY_TRACK_DIR = "/home/docker_opr/Datasets/ITLP-Campus-data/subsampled_data/outdoor/old/01_2023-02-21"

DEVICE = "cuda"

MODEL_CONFIG_PATH = "../configs/model/place_recognition/minkloc3d.yaml"
WEIGHTS_PATH = "../weights/place_recognition/minkloc3d_nclt.pth"

#### Init query dataset

The pipeline infer method accepts an input in the format of dictionary with keys in the following format:
- `"image_{camera_name}"` for images from cameras,
- `"mask_{camera_name}"` for semantic segmentation masks,
- `"pointcloud_lidar_coords"` for pointcloud coordinates from lidar,
- `"pointcloud_lidar_feats"` for pointcloud features from lidar.

The data type of all values are `torch.Tensor`.

You can load and preprocess the data manually, but in this example we will use the `opr.datasets.itlp.ITLPCampus` ` dataset class. 

In [4]:
query_dataset = ITLPCampus(
    dataset_root=QUERY_TRACK_DIR,
    sensors=["lidar"],
    mink_quantization_size=0.5,
    load_semantics=False,
    load_text_descriptions=False,
    load_text_labels=False,
    load_aruco_labels=False,
    indoor=False,
)


#### Initialize model

We will use hydra's `instantiate` function to initialize the model. The model is a `MinkLoc3D` - a simple LiDAR-only architecture.

In [5]:
model_config = OmegaConf.load(MODEL_CONFIG_PATH)
model = instantiate(model_config)

#### Initialize pipeline

The minimum requirement to initialize the `PlaceRecognitionPipeline` is that the database directory should contain the `index.faiss` file and the `track.csv` file.

The `index.faiss` file is a Faiss index, which contains the descriptors of the database. The `track.csv` file contains the metadata of the database, including the id and the pose of the descriptors.

The details on how to create the database are described in the [build_database.ipynb](./build_database.ipynb) notebook.

Note that the actual data are not required, as the pipeline will only load the `index.faiss` and the `track.csv` file. This can be useful in the real-world scenario, where the database size is too large to be stored on the local machine.

In [6]:
pipe = PlaceRecognitionPipeline(
    database_dir=DATABASE_TRACK_DIR,
    model=model,
    model_weights_path=WEIGHTS_PATH,
    device=DEVICE,
)


#### Run inference

In [7]:
sample_data = query_dataset[5]
sample_pose_gt = sample_data.pop("pose")  # removing those keys are not necessary, we just
sample_data.pop("idx")                    # want to simulate that we pass the data without GT information :)
print(f"sample_data.keys() = {sample_data.keys()}")
sample_output = pipe.infer(sample_data)
print(f"sample_output.keys() = {sample_output.keys()}")
print(f"sample_output['idx'] = {sample_output['idx']}")
print(f"pose = {sample_output['pose']}")
print(f"pose_gt = {sample_pose_gt.numpy()}")
dist_error, angle_error = compute_error(sample_output["pose"], sample_pose_gt.numpy())
print(f"dist_error = {dist_error}, angle_error = {angle_error}")


sample_data.keys() = dict_keys(['pointcloud_lidar_coords', 'pointcloud_lidar_feats'])
sample_output.keys() = dict_keys(['idx', 'pose', 'descriptor'])
sample_output['idx'] = 6
pose = [ 6.40806188e-01 -6.96985360e+00 -2.62666965e+00  2.23428939e-03
  1.21724469e-02  3.57296189e-01  9.33909135e-01]
pose_gt = [-0.3476145  -7.5303183  -1.8204867  -0.01149435  0.01080806  0.3418056
  0.9396382 ]
dist_error = 1.3932074823071565, angle_error = 2.466076215796548


## Usage example - Pointcloud Registration Pipeline

### Config

In [2]:
TRACK_DIR = "/home/docker_opr/Datasets/ITLP-Campus-data/subsampled_data/indoor/00_2023-10-25-night/floor_1"

REGISTRATION_MODEL_CONFIG_PATH = "../configs/model/registration/geotransformer_kitti.yaml"
REGISTRATION_WEIGHTS_PATH = "../weights/registration/geotransformer_kitti.pth"

### Init dataset

For the demonstration purpose, we will use the `opr.datasets.itlp.ITLPCampus` dataset class to load the data.

We will instantiate only one track and test the registration performance by evaluating the transformation between the two consecutive frames.

In [3]:
dataset = ITLPCampus(
    dataset_root=TRACK_DIR,
    sensors=["lidar"],
    mink_quantization_size=0.5,
    load_semantics=False,
    load_text_descriptions=False,
    load_text_labels=False,
    load_aruco_labels=False,
    indoor=False,
)

### Init model

In [4]:
geotransformer = instantiate(OmegaConf.load(REGISTRATION_MODEL_CONFIG_PATH))


### Init Pipeline

In [5]:
registration_pipe = PointcloudRegistrationPipeline(
    model=geotransformer,
    model_weights_path=REGISTRATION_WEIGHTS_PATH,
    device="cuda",  # the GeoTransformer currently only supports CUDA
    voxel_downsample_size=0.3,  # recommended for geotransformer_kitti configuration
)

### Run inference

In [24]:
i = 3
db_pc = dataset[i-1]["pointcloud_lidar_coords"]
query_pc = dataset[i]["pointcloud_lidar_coords"]
db_pose = pose_to_matrix(dataset[i-1]["pose"])
query_pose = pose_to_matrix(dataset[i]["pose"])
# we want to find the transformation from the "database" pose to the "query" pose
gt_transformation = np.linalg.inv(db_pose) @ query_pose

estimated_transformation = registration_pipe.infer(query_pc, db_pc)

print(f"gt_transformation = \n{gt_transformation}\n")
print(f"estimated_transformation = \n{estimated_transformation}\n")

rre, rte = compute_registration_error(gt_transformation, estimated_transformation)
print(f"Relative Rotation Error (RRE) = {rre:0.3f}\nRelative Translation Error (RTE) = {rte:0.3f}\n")

gt_transformation = 
[[ 0.62815438  0.77747642 -0.03086264  0.95043122]
 [-0.77807516  0.62788344 -0.01901165 -0.29708926]
 [ 0.00459703  0.0359557   0.99934281  0.02541637]
 [ 0.          0.          0.          1.        ]]

estimated_transformation = 
[[ 0.63717115  0.77047485 -0.01952516  1.1074791 ]
 [-0.77067107  0.6366326  -0.0276524  -0.06237316]
 [-0.00887516  0.03266682  0.9994269   0.0161792 ]
 [ 0.          0.          0.          1.        ]]

Relative Rotation Error (RRE) = 1.039
Relative Translation Error (RTE) = 0.283



/home/docker_opr/OpenPlaceRecognition/third_party/GeoTransformer/geotransformer/modules/geotransformer/superpoint_matching.py:44: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  ref_sel_indices = corr_indices // matching_scores.shape[1]


In [25]:
print(f"gt_pose = \n{query_pose}")
print(f"optimized_pose = \n{db_pose @ estimated_transformation}")

gt_pose = 
[[ 0.61203326  0.78962221 -0.04372709  2.97850537]
 [-0.78974521  0.61315495  0.01853377 -0.18161125]
 [ 0.04144616  0.02318998  0.99887158  0.14517449]
 [ 0.          0.          0.          1.        ]]
optimized_pose = 
[[ 0.62136691  0.78284234 -0.03257031  3.14041519]
 [-0.78302508  0.62191456  0.00967767  0.04942517]
 [ 0.027832    0.01949002  0.9994226   0.12941422]
 [ 0.          0.          0.          1.        ]]
